version: "3"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=company
      - POSTGRES_USER=company
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - company

networks:
  company:
    labels:
      - company