server:
  port: 8080
  servlet:
    context-path: /api/company

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: company

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
